package org.koitharu.kotatsu.parsers.site.pam.fr

import org.koitharu.kotatsu.parsers.MangaLoaderContext
import org.koitharu.kotatsu.parsers.MangaSourceParser
import org.koitharu.kotatsu.parsers.model.MangaParserSource
import org.koitharu.kotatsu.parsers.site.pam.PamParser

@MangaSourceParser("EPSILONSOFT", "EpsilonSoft", "fr")
internal class EpsilonSoft(context: MangaLoaderContext) :
	PamParser(context, MangaParserSource.EPSILONSOFT, "epsilonsoft.to") {

	override val genres = listOf(
		"Action" to "action",
		"Ahegao" to "ahegao",
		"Anal" to "anal",
		"Anime bl" to "anime-bl",
		"Arts martiaux" to "arts-martiaux",
		"Aventure" to "aventure",
		"Bdsm" to "bdsm",
		"Bondage" to "bondage",
		"Boys love" to "boys-love",
		"Bureau" to "bureau",
		"Campus" to "campus",
		"Comédie" to "comedie",
		"Comics" to "comics",
		"Cosplay" to "cosplay",
		"Coup d'un soir" to "coup-dun-soir",
		"Dark skin" to "dark-skin",
		"Démon/démone" to "demondemone",
		"Différence d'âge" to "difference-dage",
		"Doujinshi" to "doujinshi",
		"Drame" to "drame",
		"Échangisme" to "echangisme",
		"Elf" to "elf",
		"Espion" to "espion",
		"Exhibitionniste" to "exhibitionniste",
		"Fantaisie" to "fantaisie",
		"Fantastique" to "fantastique",
		"Fétichisme" to "fetichisme",
		"Furry" to "furry",
		"Gangster" to "gangster",
		"Gender bender" to "gender-bender",
		"Girls love" to "girls-love",
		"Gros seins" to "gros-seins",
		"Guideverse" to "guideverse",
		"Hardcore" to "hardcore",
		"Harem" to "harem",
		"Historique" to "historique",
		"Horreur" to "horreur",
		"Hypnose" to "hypnose",
		"Ia" to "ia",
		"Immoral" to "immoral",
		"Isekai" to "isekai",
		"Jeux vidéo" to "jeux-video",
		"Josei" to "josei",
		"Magie" to "magie",
		"Manga bl" to "manga-bl",
		"Manga h" to "manga-h",
		"Manga josei" to "manga-josei",
		"Mature" to "mature",
		"Médical" to "medical",
		"Milf" to "milf",
		"Mini-série" to "mini-serie",
		"Moderne" to "moderne",
		"Muscle" to "muscle",
		"Mystère" to "mystere",
		"Noblesse" to "noblesse",
		"Non-censuré" to "non-censure",
		"Novel" to "novel",
		"Ntr" to "ntr",
		"Omégaverse" to "omegaverse",
		"One shot" to "one-shot",
		"Percing" to "percing",
		"Plan à 3" to "plan-a-3",
		"Pornhwa" to "pornhwa",
		"Professeur" to "professeur",
		"Psychologique" to "psychologique",
		"Réincarnation" to "reincarnation",
		"Romance" to "romance",
		"Science-fiction" to "science-fiction",
		"Showbiz" to "showbiz",
		"Smut" to "smut",
		"Spanking" to "spanking",
		"Sports" to "sports",
		"Succube" to "succube",
		"Surnaturel" to "surnaturel",
		"Système" to "systeme",
		"Thriller" to "thriller",
		"Tragédie" to "tragedie",
		"Tranche de vie" to "tranche-de-vie",
		"Triangle amoureux" to "triangle-amoureux",
		"Tsundere" to "tsundere",
		"Vampire" to "vampire",
		"Vengeance" to "vengeance",
		"Vie scolaire" to "vie-scolaire",
		"Webtoon" to "webtoon",
	)
}
